### ISSUE TITLE
Which course to follow

### ISSUE THREAD

**Issue by Shivugorty** [SandeepTukkunor/Machine_Lerarning_projects#1]
I am a beginner and want to take next steps in ML and DL. So What best free resources would you recommend

**Comment by SandeepTukkunor** [comment]
I would recommend learning basic libraries first, like bumpy, pandas, matplotlib, and seaborn. All these are covered by Youtuber named Keith Galli.  Later you can go for Machine Learning Section. 

For this, I would recommend Andrew Ng's Machine Learning course from Coursera. Later You can start Deep Learning.

I hope this Helps

**Comment by Shivugorty** [comment]
Thank You
